Repository Stageus/shoot-react, pull requests merged in 2023-01, with the labels that each got.

#9 Seongmin
  public/assets/images/search.svg
  public/assets/images/shootLogo.svg
  public/assets/images/uploadPlus.svg
  src/components/header/HeaderAlarm.js
  src/components/header/HeaderComponent.js
Labels: Feat

#11 Seongmin
  public/assets/images/bookmark.svg
  public/assets/images/bookmarkFill.svg
  public/assets/images/comment.svg
  public/assets/images/postContent.svg
  src/components/main/PostDetail.js
Labels: Feat

#12 Refactor: Basic Components theme 적용
  src/components/basic/Button.js
  src/components/basic/Div.js
  src/components/basic/H.js
  src/components/basic/Img.js
  src/components/basic/Input.js
  src/components/basic/P.js
Labels: Refactor

#13 Refactor: IconText Color 추가
  src/components/common/IconText.js
Labels: Refactor

#14 Feat: svg 추가
  public/assets/images/bulb.svg
  public/assets/images/hot.svg
  public/assets/images/menuArrow.svg
  public/assets/images/menuArrowClicked.svg
  public/assets/images/star.svg
  public/assets/images/subscribe.svg
  public/assets/images/viewRecord.svg
  src/components/nav/Nav.js
Labels: Feat

#15 Refactor: Basic Components를 제외한 나머지 Components에 theme 적용
  src/components/basic/Button.js
  src/components/basic/Div.js
  src/components/basic/H.js
  src/components/basic/Img.js
  src/components/basic/Input.js
  src/components/basic/P.js
  src/components/common/CountdownTimer.js
  src/components/common/Hashtag.js
  src/components/common/IconText.js
  src/components/common/Modal.js
  src/components/common/PostItem.js
  src/components/common/Profile.js
  src/components/common/SeeMore.js
  src/components/common/TextCounter.js
  src/components/header/HeaderAlarm.js
  src/components/header/HeaderComponent.js
  src/components/header/HeaderFunctionComponent.js
  src/components/header/HeaderSearchComponent.js
  src/components/main/PostDetail.js
  src/components/post/PostComponent.js
  src/components/post/PostDetailComponent.js
  src/components/post/PostDetailLink.js
  src/components/post/PostDetailNav.js
  src/pages/BookmarkPage.js
  src/pages/CategoryPage.js
  src/pages/HashtagPage.js
  src/pages/HistoryPage.js
  src/pages/HomePage.js
  src/pages/HotPage.js
  src/pages/PostDetailPage.js
  src/pages/SearchPage.js
  src/pages/SubscribePage.js
  src/recoil/headerState.js
  src/recoil/postState.js
Labels: Refactor

#21 Fix: ChannelVideoComponent export 오류 수정, ChannelHeaderComponent 오타 수정
  src/components/channel/ChannelHeaderComponent.js
  src/components/channel/ChannelVideoComponent.js
Labels: Fix

#22 Seongmin
  src/components/post/PostDetailBookmarkIcon.js
  src/components/post/PostDetailComponent.js
  src/components/post/PostDetailLikeIcon.js
  src/components/post/PostDetailLinkList.js
  src/components/post/PostDetailSubscribeButton.js
  src/pages/post/BookmarkPage.js
  src/pages/post/CategoryPage.js
  src/pages/post/HashtagPage.js
  src/pages/post/HistoryPage.js
  src/pages/post/HomePage.js
  src/pages/post/HotPage.js
  src/pages/post/PostDetailPage.js
  src/pages/post/SearchPage.js
  src/pages/post/SubscribePage.js
Labels: Feat, Fix, Refactor

#16 Feat: svg 추가
  public/assets/images/add.svg
  public/assets/images/adminSearch.svg
  public/assets/images/catAdd.svg
  public/assets/images/category.svg
  public/assets/images/delete.svg
  public/assets/images/downArrow.svg
  public/assets/images/email.svg
  public/assets/images/largeShootLogo.svg
  public/assets/images/log.svg
  public/assets/images/password.svg
  public/assets/images/stats.svg
  src/components/account/AccountEmailFormComponent.js
  src/components/account/AccountLocalLoginFormComponent.js
  src/components/account/AccountPasswordFormComponent.js
  src/components/account/AccountPersonalFormComponent.js
  src/components/account/AccountSocialLoginFormComponent.js
  src/components/account/EventInput.js
  src/components/account/SmallEventInput.js
  src/components/admin/AdminCategoryRequestComponent.js
  src/components/admin/AdminCategoryUpdateComponent.js
  src/components/admin/AdminLogComponent.js
  src/components/admin/AdminReportChannel.js
  src/components/admin/AdminReportComment.js
  src/components/admin/AdminReportComponent.js
  src/components/admin/AdminReportPost.js
  src/components/admin/AdminReportReplyComment.js
  src/components/admin/AdminStatisticsComponent.js
  src/components/nav/AdminNavComponent.js
  src/components/nav/Nav.js
  src/components/nav/NavComponent.js
  src/components/nav/NavHashtag.js
  src/components/nav/NavItem.js
  src/hooks/useFocusInput.js
  src/hooks/useInput.js
  src/hooks/useValidationInput.js
  src/pages/account/FindPasswordPage.js
  src/pages/account/LoginPage.js
  src/pages/account/ResetPasswordPage.js
  src/pages/account/SignupPage.js
  src/pages/admin/AdminPage.js
Labels: Feat, Refactor, Rename, Comment

#23 Feat: 모달 추가
  src/components/modal/Modal.js
Labels: Feat

#24 Feat: PostItemListComponent 제작 및 적용
  src/components/common/PostItemListComponent.js
  src/components/post/PostComponent.js
  src/pages/post/BookmarkPage.js
  src/pages/post/CategoryPage.js
  src/pages/post/HashtagPage.js
  src/pages/post/HistoryPage.js
  src/pages/post/HomePage.js
  src/pages/post/HotPage.js
  src/pages/post/PostDetailPage.js
  src/pages/post/SearchPage.js
  src/pages/post/SubscribePage.js
Labels: Feat
