Repository Stageus/shoot-react, pull requests merged in 2023-02, with the labels that each got.

#25 Seongmin
  public/assets/images/closeBlack.svg
  public/assets/images/replyCommentArrow.svg
  public/assets/images/replyCommentArrowOpen.svg
  src/components/common/IconText.js
  src/components/common/PostItem.js
  src/components/common/Profile.js
  src/components/modal/post/Comment.js
  src/components/modal/post/CommentInput.js
  src/components/modal/post/CommentModalComponent.js
  src/components/modal/post/PostDetailModalComponent.js
  src/components/modal/post/PostDetailVote.js
  src/components/modal/post/PostDetailVoteListComponent.js
  src/components/post/PostChannelListComponent.js
  src/components/post/PostComponent.js
  src/components/post/PostDetailComponent.js
  src/components/post/PostDetailNav.js
  src/hooks/useReplyInput.js
  src/pages/post/BookmarkPage.js
  src/pages/post/CategoryPage.js
  src/pages/post/HashtagPage.js
  src/pages/post/HistoryPage.js
  src/pages/post/HomePage.js
  src/pages/post/HotPage.js
  src/pages/post/PostDetailPage.js
  src/pages/post/SearchPage.js
  src/pages/post/SubscribePage.js
  src/recoil/postState.js
Labels: Feat

#26 Refactor: Div background-color, border-bottom 수정
  src/components/basic/Div.js
Labels: Refactor

#27 Fix: Input 컴포넌트가 바뀜에 따른 import 수정
  src/components/header/HeaderSearchComponent.js
Labels: Fix

#29 Fix: Input 컴포넌트 경로 수정
  public/assets/images/catAddClicked.svg
  public/assets/images/categoryClicked.svg
  public/assets/images/hotClicked.svg
  public/assets/images/logClicked.svg
  public/assets/images/reportClicked.svg
  public/assets/images/starClicked.svg
  public/assets/images/statsClicked.svg
  public/assets/images/subscribeClicked.svg
  public/assets/images/viewRecordClicked.svg
  src/components/account/AccountEmailFormComponent.js
  src/components/account/AccountLocalLoginFormComponent.js
  src/components/account/AccountPasswordFormComponent.js
  src/components/account/AccountPersonalFormComponent.js
  src/components/account/AccountSocialLoginFormComponent.js
  src/components/account/EventInput.js
  src/components/account/SmallEventInput.js
  src/components/admin/AdminCategoryRequestComponent.js
  src/components/admin/AdminCategoryUpdateComponent.js
  src/components/admin/AdminLogComponent.js
  src/components/admin/AdminReportChannel.js
  src/components/admin/AdminReportComment.js
  src/components/admin/AdminReportComponent.js
  src/components/admin/AdminReportPost.js
  src/components/admin/AdminReportReplyComment.js
  src/components/admin/AdminStatisticsComponent.js
  src/components/admin/AdminTable.js
  src/components/nav/AdminNavComponent.js
  src/components/nav/NavComponent.js
  src/components/nav/NavItem.js
  src/pages/admin/AdminPage.js
Labels: Feat, Fix, Refactor, Design

#30 Feat: admin 모달의 신고 테이블 생성
  src/components/admin/AdminTable.js
  src/components/modal/admin/AdminModalTable.js
  src/components/nav/AdminNavComponent.js
  src/components/nav/NavCategoryItem.js
  src/components/nav/NavComponent.js
  src/components/nav/NavItem.js
Labels: Feat, Fix, Refactor, Style

#31 Feat: 댓글 좋아요 버튼 hook으로 기능 구현
  src/components/common/PostItem.js
  src/components/common/Profile.js
  src/components/common/SeeMore.js
  src/components/modal/post/Comment.js
  src/components/modal/post/CommentLike.js
  src/components/modal/post/CommentModalComponent.js
  src/components/post/PostDetailLinkList.js
  src/hooks/useCommentLike.js
  src/hooks/useLinkListIdx.js
  src/hooks/useReplyInput.js
  src/hooks/useToggle.js
  src/recoil/postState.js
Labels: Feat, Fix, Refactor, Rename

#32 Feat: 투표 정보 state로 관리
  src/components/modal/post/PostDetailVote.js
  src/components/modal/post/PostDetailVoteListComponent.js
  src/recoil/postState.js
Labels: Feat, Fix, Refactor

#33 Feat: 로그인 정보와 유저 정보 관리
  src/components/common/IconText.js
  src/components/header/HeaderFunctionComponent.js
  src/components/modal/post/Comment.js
  src/components/modal/post/CommentInput.js
  src/components/modal/post/CommentLike.js
  src/components/modal/post/PostDetailVote.js
  src/components/post/PostDetailBookmarkIcon.js
  src/components/post/PostDetailComponent.js
  src/components/post/PostDetailLikeIcon.js
  src/components/post/PostDetailSubscribeButton.js
Labels: Feat, Fix

#35 Feat: 시간 차이 계산하는 hook 구현
  src/components/header/HeaderAlarm.js
  src/components/header/HeaderAlarmBox.js
  src/components/modal/post/Comment.js
  src/components/modal/post/PostDetailModalComponent.js
  src/components/post/PostDetailComponent.js
  src/hooks/useDifferenceTime.js
  src/pages/post/PostDetailPage.js
  src/recoil/headerState.js
  src/recoil/postState.js
Labels: Feat

#37 Refactor: 헤더 컴포넌트 분리
  src/components/header/HeaderAlarm.js
  src/components/header/HeaderAlarmListComponent.js
  src/components/header/HeaderSearchComponent.js
  src/components/header/HeaderSearchHistortyAutoSave.js
  src/components/header/HeaderSearchHistoryListComponent.js
Labels: Refactor

#36 Design: placeholder 수정
  src/components/account/AccountEmailFormComponent.js
  src/components/account/AccountLocalLoginFormComponent.js
  src/components/account/AccountPasswordFormComponent.js
  src/components/account/AccountPersonalFormComponent.js
  src/components/admin/AdminLogComponent.js
  src/components/admin/AdminTable.js
  src/components/nav/NavComponent.js
  src/pages/account/SignupPage.js
  src/recoil/accountState.js
  src/recoil/adminState.js
  src/recoil/navState.js
Labels: Feat, Fix, Refactor, Design

#38 Feat: Modal, App.js 추가
  public/index.html
  src/App.js
  src/components/modal/AlertModal.js
  src/components/modal/ConfirmModal.js
  src/components/modal/Modal.js
  src/components/modal/ModalContainer.js
  src/index.js
  src/recoil/modalState.js
Labels: Feat

#40 Feat: 댓글, 포스트 디테일 모달 열기 기능 추가
  src/components/header/HeaderSearchComponent.js
  src/components/modal/Modal.js
  src/components/modal/post/CommentModalComponent.js
  src/components/modal/post/PostDetailModalComponent.js
  src/components/post/PostDetailComponent.js
  src/pages/post/SearchPage.js
Labels: Feat, Fix

#41 Feat: 채널 검색 기록 결과 화면 구현
  src/components/common/SeeMore.js
  src/components/modal/Modal.js
  src/components/modal/post/Comment.js
  src/components/modal/post/CommentInput.js
  src/components/post/SearchChannel.js
  src/components/post/SearchChannelListComponent.js
  src/pages/post/SearchPage.js
  src/recoil/postState.js
Labels: Feat, Fix

#42 Feat: top hashtag 상태관리
  src/components/account/AccountEmailFormComponent.js
  src/components/account/EventInput.js
  src/components/nav/NavCategoryItem.js
  src/components/nav/NavComponent.js
  src/components/nav/NavHashtag.js
  src/recoil/navState.js
Labels: Feat

#43 Feat: 포스트 아이템 및 프로필 기본 이미지 추가
  src/components/common/PostItem.js
  src/components/common/Profile.js
Labels: Feat

#46 Feat: 로그인 시 유저 토큰 상태관리
  src/components/account/AccountLocalLoginFormComponent.js
  src/recoil/accountState.js
Labels: Feat

#48 Feat: 관리자 페이지 카테고리 삭제 추가 기능
  src/components/account/AccountLocalLoginFormComponent.js
  src/components/admin/AdminTable.js
  src/components/nav/NavComponent.js
  src/recoil/adminState.js
Labels: Feat, Fix

#49 Feat: 상위 해시태그 데이터 삽입
  src/components/account/AccountEmailFormComponent.js
  src/components/account/AccountPasswordFormComponent.js
  src/components/admin/AdminLogComponent.js
  src/components/admin/AdminTable.js
  src/components/modal/admin/AdminModalTable.js
  src/components/nav/AdminNavComponent.js
  src/components/nav/NavHashtag.js
  src/pages/account/ResetPasswordPage.js
  src/recoil/navState.js
Labels: Feat, Fix, Refactor

#50 Fix: 링크가 잘리는 버그 수정
  src/components/basic/P.js
  src/components/modal/post/CommentInput.js
  src/components/modal/post/PostDetailVote.js
  src/components/post/PostDetailBookmarkIcon.js
  src/components/post/PostDetailLikeIcon.js
  src/components/post/PostDetailLink.js
  src/components/post/PostDetailNav.js
  src/components/post/PostDetailSubscribeButton.js
  src/pages/post/BookmarkPage.js
  src/pages/post/HistoryPage.js
  src/pages/post/HomePage.js
  src/pages/post/HotPage.js
  src/pages/post/PostDetailPage.js
  src/pages/post/SubscribePage.js
Labels: Feat, Fix

#52 Fix: svg 경로 수정
  src/components/account/AccountEmailFormComponent.js
  src/components/admin/AdminTable.js
  src/components/modal/Modal.js
  src/components/modal/admin/AdminModalTable.js
  src/components/modal/admin/BlockButton.js
  src/components/modal/admin/BlockModalComponent.js
  src/components/modal/admin/CloseButton.js
  src/pages/account/ResetPasswordPage.js
  src/recoil/accountState.js
  src/recoil/adminState.js
Labels: Feat, Fix

#53 Feat: 댓글 대댓글 불러오는 api 적용
  public/assets/images/emptyBang.svg
  src/components/common/PostItem.js
  src/components/common/PostItemListComponent.js
  src/components/modal/post/Comment.js
  src/components/modal/post/CommentLike.js
  src/components/modal/post/CommentModalComponent.js
  src/components/post/PostComponent.js
  src/components/post/PostDetailComponent.js
  src/components/post/SearchChannelListComponent.js
  src/pages/post/BookmarkPage.js
  src/pages/post/HistoryPage.js
  src/pages/post/HomePage.js
  src/pages/post/HotPage.js
  src/pages/post/PostDetailPage.js
  src/pages/post/SearchPage.js
  src/pages/post/SubscribePage.js
  src/recoil/headerState.js
  src/recoil/postState.js
Labels: Feat, Refactor, Design

#54 Feat: useFetch에 put 기능 추가
  src/components/basic/Img.js
  src/components/common/IconText.js
  src/components/common/PostItem.js
  src/components/common/Profile.js
  src/components/header/HeaderFunctionComponent.js
  src/components/header/HeaderSearchComponent.js
  src/components/modal/post/Comment.js
  src/components/modal/post/CommentInput.js
  src/components/modal/post/CommentLike.js
  src/components/modal/post/PostDetailVote.js
  src/components/post/PostChannelListComponent.js
  src/components/post/PostDetailBookmarkIcon.js
  src/components/post/PostDetailComponent.js
  src/components/post/PostDetailLikeIcon.js
  src/components/post/PostDetailNav.js
  src/components/post/PostDetailSubscribeButton.js
  src/components/post/SearchChannel.js
  src/components/post/SearchChannelListComponent.js
  src/hooks/useFetch.js
  src/pages/post/CategoryPage.js
  src/pages/post/HashtagPage.js
  src/pages/post/HistoryPage.js
  src/pages/post/HotPage.js
  src/pages/post/SearchPage.js
  src/pages/post/SubscribePage.js
Labels: Feat, Design

#55 Feat: 비밀번호 찾기 페이지
  src/components/account/AccountEmailFormComponent.js
  src/components/account/AccountHeaderComponent.js
  src/components/account/AccountLocalLoginFormComponent.js
  src/components/account/AccountPasswordFormComponent.js
  src/components/account/AccountPersonalFormComponent.js
  src/components/common/EventInput.js
  src/components/common/SmallEventInput.js
  src/components/modal/admin/AdminModalTable.js
  src/components/modal/admin/BlockModalComponent.js
  src/pages/account/FindPasswordPage.js
  src/pages/account/LoginPage.js
  src/pages/account/ResetPasswordPage.js
  src/pages/account/SignupPage.js
  src/recoil/accountState.js
Labels: Feat, Rename

#56 Refactor: Profile 구독 기능 추가
  src/components/common/Profile.js
Labels: Refactor

#57 Feat, Refactor: 채널 페이지 api 적용
  package-lock.json
  package.json
  public/assets/images/checkOff.svg
  public/assets/images/checkOn.svg
  public/assets/images/pencil.svg
  public/assets/images/upload.svg
  src/components/channel/ChannelHeaderComponent.js
  src/components/channel/ChannelHeaderProfile.js
  src/components/channel/ChannelInfoComponent.js
  src/components/channel/ChannelModifyComponent.js
  src/components/channel/ChannelTabComponent.js
  src/components/common/LargeEventInput.js
  src/components/modal/Modal.js
  src/components/modal/channel/ChannelThumbnailModal.js
  src/pages/channel/ChannelPage.js
  src/recoil/channelState.js
Labels: Feat, Refactor, Design

#59 Refactor: 채널 수정 페이지 url 변경 및 input 속성 추가
  src/App.js
  src/components/basic/Input.js
  src/components/channel/ChannelTabComponent.js
  src/components/common/LargeEventInput.js
  src/components/upload/UploadComponent.js
  src/components/upload/UploadHashTag.js
  src/components/upload/UploadLink.js
  src/components/upload/UploadRadio.js
  src/components/upload/UploadVote.js
  src/recoil/uploadState.js
Labels: Feat, Refactor

#60 Design: 관리자 페이지 신고 모달 디자인 변경
  public/assets/images/sort.svg
  src/components/account/AccountLocalLoginFormComponent.js
  src/components/admin/AdminCategoryUpdateComponent.js
  src/components/admin/AdminReportComponent.js
  src/components/admin/AdminTable.js
  src/components/modal/admin/AdminModalTable.js
  src/components/modal/admin/BlockModalComponent.js
  src/components/nav/NavComponent.js
  src/pages/account/SignupPage.js
  src/recoil/adminState.js
Labels: Feat, Refactor, Design

#61 Feat: 더보기의 삭제, 수정 기능 추가
  src/components/channel/ChannelHeaderComponent.js
  src/components/common/SeeMore.js
  src/components/header/HeaderFunctionComponent.js
  src/components/modal/post/CommentInput.js
  src/components/modal/post/CommentModalComponent.js
Labels: Feat, Fix

#63 Feat: 로그아웃 기능 구현
  public/assets/images/postThumbnail.png
  src/components/common/PostItem.js
  src/components/header/HeaderFunctionComponent.js
Labels: Feat, Design

#64 Feat: 카테고리 요청 alert 추가
  src/components/admin/AdminCategoryUpdateComponent.js
  src/components/modal/Modal.js
  src/components/modal/admin/AddCategoryModalComponent.js
  src/components/nav/NavComponent.js
Labels: Feat
